apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessMode:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      storageClassName: default
