apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq
spec:
  selector:
    matchLabels:
      app: vpromq
  template:
    metadata:
      labels:
        app: vpromq
    spec:
      containers:
      - name: vpromq
        image: rabbitmq
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
